### ISSUE TITLE
Link to latest build is broken

### ISSUE THREAD

**Issue by sammarcus** [7hil/mac_ear_control#1]
Hi,

The link is dead in step 1 in Usage. 

Thank you!

**Comment by 7hil** [comment]
Try [this one](https://github.com/7hil/mac_ear_control/releases/download/0.1/mac_ear_control.app.zip)

**Comment by sammarcus** [comment]
ah thank you!

**Comment by 7hil** [comment]
Could you provide your OS version if the app works? 
I only test it on my Mac so not sure whether it will work or not on other OS.
If it doesn't work, please let me know.

Thank you.

**Comment by sammarcus** [comment]
I'm on 10.12 and it works perfectly!!! 😍 Thanks, Peihao!

**Comment by 7hil** [comment]
macOS 10.12 Sierra Preview? Thanks! Glad to hear it works.

**Comment by sammarcus** [comment]
Build 16A320 so yes, I think so!
