### ISSUE TITLE
next/prev no longer working under 10.12.4

### ISSUE THREAD

**Issue by KTachibanaM** [7hil/mac_ear_control#4]
After updating to 10.12.4, next/prev is no longer working (for Spotify, and another music player that used to recognize next/prev before updating). Play/pause and volume are still working.

**Comment by 7hil** [comment]
Seems the code can't catch the next/prev event under 10.12.4, all it get are play events. Currently I couldn't find a way to capture next/prev events.

**Comment by KTachibanaM** [comment]
Is it possible to simulate it in software and make a optional config for delay between single clicks? I really liked this utility and would like it to work on 10.12.4.

**Comment by 7hil** [comment]
It is possible but it's a bit complicated for me. I'm new to Mac App Programming and this will take some time. I will try it when I have time.

**Comment by morgangalpin** [comment]
Your app is very useful; thanks for making it.

Play/pause works for me in 10.12.4, but the events are also being picked up by iTunes now. This wasn't happening previously. However, a workaround for this is to start Quicktime Player and just leave it running in the background. Having it open will prevent iTunes from being opened on the play/pause event.

http://apple.stackexchange.com/questions/52353/headphone-play-pause-button-controls-itunes-only

**Comment by stek29** [comment]
So what happened is apple finally fixed the button. Now it sends `kHIDUsage_Csmr_PlayOrPause`, which is successfully picked up by Spotify and other apps. You can see `Unknown key press seen 205` in logs, and `kHIDUsage_Csmr_PlayOrPause` is `0xCD`.

The issue is it still launches iTunes. Unloading rcd service works for me.

Oh, and of course Next/Prev is now broken. I think we'd have to use some timers and capture the play/pause somehow.

**Comment by stek29** [comment]
Maybe this would have to use something like https://github.com/nevyn/SPMediaKeyTap

**Comment by stek29** [comment]
Here's my current implementation: https://github.com/stek29/mac_ear_control/tree/clicks-timer

It has two issues:
- It doesn't stop Play/Pause key from activating other apps (I don't know how to do this tbh)
- It has hardcoded timer delay

**Comment by morgangalpin** [comment]
Is there a release with these latest changes?

**Comment by stek29** [comment]
Btw, Spotify (v 1.0.65.320.gac7a8e02) seems to work fine even without mac_ear_control (at least on High Sierra)
It also seems to stop itunes from starting.
Probably someone should try to reverse their app and see how exactly do they handle this. I hope they don't do it the way I do.

**Comment by stek29** [comment]
Looks like they really do it the same way I do it, based on how it works when other apps are listening for play/pause key :X
