### ISSUE TITLE
iTunes block no longer works under 10.12.4

### ISSUE THREAD

**Issue by jo3p** [7hil/mac_ear_control#5]
After updating to 10.12.4, iTunes pops up whenever I use my earphone controls and starts 'intercepting' the control.
EDIT: iTunes does not 'intercept' the earphone controls, it just launches.

**Comment by 7hil** [comment]
In mac_ear_control we use `/bin/launchctl unload /System/Library/LaunchAgents/com.apple.rcd.plist` to block iTunes. But under 10.12.4, System Integrity Protection (SIP)  prevent us from unloading the rcd(remote control deamon), so it is no longer working.

To make the block works, you can try [this tool](https://thebitguru.com/projects/itunes-patch) suggested by [this answer](http://apple.stackexchange.com/a/174115/135691).

**Comment by jo3p** [comment]
Now I remember, I already patched the iTunes problem with the tool suggested, but the SIP unpatched it after updating to 10.12.4. Thanks for the suggestion, I patched it again now.
